runtime: custom
env: flex

# instance_class: F2


env_variables:
  DATABASE_URL: "postgress://doadmin:3TfPHMUJtuYznpzd@db-postgresql-blr1-07596-do-user-9368613-0.b.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
  DATABASE_HOST: "postgress://doadmin:3TfPHMUJtuYznpzd@db-postgresql-blr1-07596-do-user-9368613-0.b.db.ondigitalocean.com"

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
network:
  name: projects/tidal-heading-348407/global/networks/vpc-p-shared-common
  subnetwork_name: sb-p-shared-prod-mum-net1

manual_scaling:
  instances: 1

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 16
